### ISSUE TITLE
Automatically wrap observer is not work with expo/react-native

### ISSUE THREAD

**Issue by aitimate** [noru/use-mobx#1]
pls

**Comment by noru** [comment]
I'm not familiar with react-native. Have you tried the official mobx-react-lite instead? It may be a better choice for react-native, cuz I won't be able to test thoroughly for RN

**Comment by aitimate** [comment]
> I'm not familiar with react-native. Have you tried the official mobx-react-lite instead? It may be a better choice for react-native, cuz I won't be able to test thoroughly for RN

I tried, not work. I found an old solution, but it's only work for arrow-func-jsx... maybe i should try to update the code: https://github.com/re-js/babel-plugin-jsx-wrapper

**Comment by noru** [comment]
Same as #2
